### ISSUE TITLE
Websockets for real time updates

### ISSUE THREAD

**Issue by Kagiri2** [shimupan/lineupx#246]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Implement Websockets for real time updates. Should be able to have at least 1k connections without overloading server.

**Comment by shimupan** [comment]
That sounds like a good idea but what should we use websockets for? A real-time messaging between users?

**Comment by Kagiri2** [comment]
that could work, but mainly like youtube with views incrementing automatically and comments and likes/dislike updating in real time.
