### ISSUE TITLE
saved posts not showing

### ISSUE THREAD

**Issue by Kagiri2** [shimupan/lineupx#350]
**Is your feature request related to a problem? Please describe.**
<-- A clear and concise description of what the problem is. -->

**Describe the solution you'd like**
<-- A clear and concise description of what you want to happen. -->

the new user stuff made a bug where the saved posts no longer show

**Comment by shimupan** [comment]
Yep, simple fix tho: src/web/src/Pages/user/ProfilePage.tsx line 88 need to add "saved"
