### ISSUE TITLE
Autoscroll small posts when user hovers

### ISSUE THREAD

**Issue by shimupan** [shimupan/lineupx#359]
**Is your feature request related to a problem? Please describe.**
<-- A clear and concise description of what the problem is. -->

**Describe the solution you'd like**
<-- A clear and concise description of what you want to happen. -->

Similar to how YouTube plays a mini video when you hover over a post, we should make our version where we play a small slideshow over the 3 images

**Comment by Kagiri2** [comment]
that looks ugly tho did we not try that
